#!/usr/bin/env bash
# E資格トレーニングのデイリーフォローアップ。
# plan.md から今日のタスクを、progress.md から進捗を読み取り、
# トラッキングIssueにコメントする。GitHub Actions から毎朝実行される。
set -euo pipefail

START_DATE="2026-07-27" # Day 1
TOTAL_DAYS=30
PLAN="e-shikaku/plan.md"
PROGRESS="e-shikaku/progress.md"

today=$(TZ=Asia/Tokyo date +%Y-%m-%d)
day=$(( ( $(date -ud "$today" +%s) - $(date -ud "$START_DATE" +%s) ) / 86400 + 1 ))

if (( day < 1 || day > TOTAL_DAYS )); then
  echo "学習期間外 (Day $day) のためスキップ"
  exit 0
fi

issue_state=$(gh issue view "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --json state --jq .state)
if [[ "$issue_state" != "OPEN" ]]; then
  echo "Issue #$ISSUE_NUMBER はクローズ済みのためスキップ"
  exit 0
fi

# plan.md のテーブル行 "| N | 日付 | テーマ | 内容 |" から当日分を抽出
row=$(grep -E "^\| $day \|" "$PLAN" | head -1)
theme=$(echo "$row" | awk -F'|' '{print $4}' | xargs)
detail=$(echo "$row" | awk -F'|' '{print $5}' | xargs)

done_count=$(grep -c '^- \[x\] Day' "$PROGRESS" || true)
expected=$(( day - 1 ))
remaining=$(( TOTAL_DAYS - day + 1 ))

if (( done_count >= expected )); then
  status="✅ 順調です (${done_count}/${expected} 日完了)"
else
  behind=$(( expected - done_count ))
  status="⚠️ ${behind} 日分の遅れがあります (${done_count}/${expected} 日完了)。README の回収ルールに沿って週末の予備日で挽回しましょう"
fi

body=$(cat <<EOF
## 📚 Day ${day}/${TOTAL_DAYS} — ${theme}

**今日のタスク**: ${detail}

**進捗**: ${status}
**試験想定日まであと ${remaining} 日**

学習が終わったら [progress.md](https://github.com/${GITHUB_REPOSITORY}/blob/main/e-shikaku/progress.md) の Day ${day} にチェックを付けてください。

---
_Generated by [Claude Code](https://claude.ai/code)_
EOF
)

gh issue comment "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --body "$body"
echo "Day ${day} のフォローアップを Issue #${ISSUE_NUMBER} に投稿しました"
